### PR TITLE
update formatting and instructions

### PR DESCRIPTION
**Pull request by Nathan13888**

### CODE REVIEW

**Comment by Nathan13888** [comment]
@jwenjian Could you have a look at this? It's for the readme.

**Comment by Nathan13888** [comment]
Also, are you going to continue to develop this project?

**Comment by Nathan13888** [comment]
😑 @jwenjian

**Comment by jwenjian** [comment]
sry, I do not see any chance to continue update this project for now, if you want add some features, I suggest and welcome you to fork this project under your account.

**Pull request closed without merging**
